=== brandleadership/artoz_pim/website/extensioninfo.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="extensioninfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="extension" type="extensionType" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="extensionType">
		<xs:sequence>
			<xs:element name="requires-extension" type="requires-extensionType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="coremodule" type="coremoduleType" minOccurs="0" maxOccurs="1" />
			<xs:element name="junitmodule" type="junitmoduleType" minOccurs="0" maxOccurs="1" />
			<xs:element name="webmodule" type="webmoduleType" minOccurs="0" maxOccurs="1" />
			<xs:element name="hmcmodule" type="hmcmoduleType" minOccurs="0" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="classprefix" type="xs:string" use="optional" />
		<xs:attribute name="abstractclassprefix" type="xs:string" use="optional" />
		<xs:attribute name="isoldstyleextension" type="xs:boolean" use="optional" />		
		<xs:attribute name="packageroot" type="xs:string" use="optional" />
		<xs:attribute name="managername" type="xs:string" use="optional" />
		<xs:attribute name="managersuperclass" type="classType" use="optional" />
	</xs:complexType>

	<xs:complexType name="requires-extensionType">
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="coremoduleType">
		<xs:attribute name="additionalclasspath" type="xs:string" use="optional" />
		<xs:attribute name="packageroot" type="xs:string" use="optional"/>
		<xs:attribute name="manager" type="xs:string" use="optional"/>
		<xs:attribute name="sourceavailable" type="xs:boolean" use="required"/>
		<xs:attribute name="generated" type="xs:boolean" use="optional"/>
		<xs:attribute name="java5" type="xs:boolean" use="optional"/>
		<xs:attribute name="generatePartOf" type="xs:boolean" use="optional"/>
	</xs:complexType>

	<xs:complexType name="junitmoduleType">
		<xs:attribute name="additionalclasspath" type="xs:string" use="optional" />
		<xs:attribute name="sourceavailable" type="xs:boolean" use="required"/>
	</xs:complexType>

	<xs:complexType name="webmoduleType">
		<xs:attribute name="webroot" type="xs:string" use="required" />
		<xs:attribute name="additionalclasspath" type="xs:string" use="optional" />
		<xs:attribute name="jspcompile" type="xs:boolean" use="optional"/>
		<xs:attribute name="sourceavailable" type="xs:boolean" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="hmcmoduleType">
		<xs:attribute name="additionalclasspath" type="xs:string" use="optional" />
		<xs:attribute name="extensionclassname" type="xs:string" use="optional"/>
		<xs:attribute name="sourceavailable" type="xs:boolean" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="classType">
		<xs:restriction base="xs:normalizedString"/>
	</xs:simpleType>
	
</xs:schema>

=== brandleadership/artoz_pim/website/extensioninfo.xml
<?xml version="1.0"?>
<!--
 [y] hybris Platform

 Copyright (c) 2000-2008 hybris AG
 All rights reserved.

 This software is the confidential and proprietary information of hybris
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with hybris.

  
-->
<extensioninfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="extensioninfo.xsd">
   <extension  name="website"
               abstractclassprefix="Generated"
               classprefix="Website"
               managername="WebsiteManager"
               managersuperclass="de.hybris.platform.jalo.extension.Extension"
               >
               
      <!-- you should add all required extensions to this list -->         
      <requires-extension name="hmc"/>         
      <requires-extension name="impex"/> 
      <requires-extension name="cronjob"/>
      <requires-extension name="webfoundation"/>      
      <requires-extension name="cms"/>      
      <requires-extension name="artoz"/>    

      <coremodule packageroot="ch.screenconcept.artoz.website"
                  manager="ch.screenconcept.artoz.website.jalo.WebsiteManager"
                  sourceavailable="true"
                  generated="true" 
       						java5="true"
                  />

      <webmodule  jspcompile="false" 
                  sourceavailable="true"
                  webroot="/"/>

      <hmcmodule   sourceavailable="true"
                     extensionclassname="ch.screenconcept.artoz.website.hmc.WebsiteHMCExtension" />

   </extension>
      
</extensioninfo>
